"""WSGI config for the DevOps Pipeline project.

This module exposes the WSGI callable as a module-level variable named
``application``. It follows the default Django WSGI setup generated by
``django-admin startproject``.
"""

import os

from django.core.wsgi import get_wsgi_application

# Default to base settings; override via DJANGO_SETTINGS_MODULE if needed.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "devops_pipeline.settings.base")

application = get_wsgi_application()


# EOF
